theme: jekyll-theme-time-machine
lsi: false
safe: true
source: LearningPython
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
