remote_theme: vaibhavvikas/jekyll-theme-minimalistic
theme: jekyll-theme-midnight
plugins:
  - jekyll-remote-theme
lsi: false
safe: true
source: LearningPython
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
